# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './batch_geocoding_dialog.ui'
#
# Created: Wed Oct  3 13:43:25 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BatchGeocodingDialog(object):
    def setupUi(self, BatchGeocodingDialog):
        BatchGeocodingDialog.setObjectName(_fromUtf8("BatchGeocodingDialog"))
        BatchGeocodingDialog.resize(436, 392)
        BatchGeocodingDialog.setWindowTitle(QtGui.QApplication.translate("BatchGeocodingDialog", "Batch geocoding", None, QtGui.QApplication.UnicodeUTF8))
        BatchGeocodingDialog.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(BatchGeocodingDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_3 = QtGui.QFrame(BatchGeocodingDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 18, 0, 1, 4)
        self.cmbLayer = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbLayer.setObjectName(_fromUtf8("cmbLayer"))
        self.gridLayout.addWidget(self.cmbLayer, 0, 1, 1, 3)
        self.line = QtGui.QFrame(BatchGeocodingDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.line_2 = QtGui.QFrame(BatchGeocodingDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 16, 0, 1, 4)
        self.cmbGeocoder = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbGeocoder.setObjectName(_fromUtf8("cmbGeocoder"))
        self.gridLayout.addWidget(self.cmbGeocoder, 17, 1, 1, 3)
        self.chkStreet = QtGui.QCheckBox(BatchGeocodingDialog)
        self.chkStreet.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Street:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkStreet.setObjectName(_fromUtf8("chkStreet"))
        self.gridLayout.addWidget(self.chkStreet, 9, 0, 1, 1)
        self.cmbStreet = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbStreet.setEnabled(False)
        self.cmbStreet.setObjectName(_fromUtf8("cmbStreet"))
        self.gridLayout.addWidget(self.cmbStreet, 9, 1, 1, 3)
        self.cmbBuildingNum = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbBuildingNum.setEnabled(False)
        self.cmbBuildingNum.setObjectName(_fromUtf8("cmbBuildingNum"))
        self.gridLayout.addWidget(self.cmbBuildingNum, 11, 1, 1, 3)
        self.cmbAddress = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbAddress.setObjectName(_fromUtf8("cmbAddress"))
        self.gridLayout.addWidget(self.cmbAddress, 3, 1, 1, 3)
        self.lblLayer = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLayer.setFont(font)
        self.lblLayer.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblLayer.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer.setObjectName(_fromUtf8("lblLayer"))
        self.gridLayout.addWidget(self.lblLayer, 0, 0, 1, 1)
        self.frmSettlement = QtGui.QFrame(BatchGeocodingDialog)
        self.frmSettlement.setEnabled(False)
        self.frmSettlement.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmSettlement.setFrameShadow(QtGui.QFrame.Raised)
        self.frmSettlement.setObjectName(_fromUtf8("frmSettlement"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frmSettlement)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rbSettlName = QtGui.QRadioButton(self.frmSettlement)
        self.rbSettlName.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSettlName.setChecked(True)
        self.rbSettlName.setObjectName(_fromUtf8("rbSettlName"))
        self.gridLayout_3.addWidget(self.rbSettlName, 0, 0, 1, 1)
        self.rbSettlField = QtGui.QRadioButton(self.frmSettlement)
        self.rbSettlField.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "From field", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSettlField.setObjectName(_fromUtf8("rbSettlField"))
        self.gridLayout_3.addWidget(self.rbSettlField, 2, 0, 1, 1)
        self.cmbSettlField = QtGui.QComboBox(self.frmSettlement)
        self.cmbSettlField.setEnabled(False)
        self.cmbSettlField.setObjectName(_fromUtf8("cmbSettlField"))
        self.gridLayout_3.addWidget(self.cmbSettlField, 2, 1, 1, 1)
        self.txtSettlName = QtGui.QLineEdit(self.frmSettlement)
        self.txtSettlName.setObjectName(_fromUtf8("txtSettlName"))
        self.gridLayout_3.addWidget(self.txtSettlName, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frmSettlement, 8, 1, 1, 3)
        self.cmbRegion = QtGui.QComboBox(BatchGeocodingDialog)
        self.cmbRegion.setEnabled(False)
        self.cmbRegion.setObjectName(_fromUtf8("cmbRegion"))
        self.gridLayout.addWidget(self.cmbRegion, 4, 1, 1, 3)
        self.lblAddress = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAddress.setFont(font)
        self.lblAddress.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddress.setTextFormat(QtCore.Qt.PlainText)
        self.lblAddress.setWordWrap(False)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.gridLayout.addWidget(self.lblAddress, 3, 0, 1, 1)
        self.chkSettlement = QtGui.QCheckBox(BatchGeocodingDialog)
        self.chkSettlement.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Settlement:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSettlement.setObjectName(_fromUtf8("chkSettlement"))
        self.gridLayout.addWidget(self.chkSettlement, 8, 0, 1, 1)
        self.chkDistrict = QtGui.QCheckBox(BatchGeocodingDialog)
        self.chkDistrict.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "District:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDistrict.setObjectName(_fromUtf8("chkDistrict"))
        self.gridLayout.addWidget(self.chkDistrict, 6, 0, 1, 1)
        self.bottomPanel = QtGui.QWidget(BatchGeocodingDialog)
        self.bottomPanel.setObjectName(_fromUtf8("bottomPanel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.bottomPanel)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.prgProcess = QtGui.QProgressBar(self.bottomPanel)
        self.prgProcess.setProperty("value", 0)
        self.prgProcess.setObjectName(_fromUtf8("prgProcess"))
        self.horizontalLayout.addWidget(self.prgProcess)
        self.btnRun = QtGui.QPushButton(self.bottomPanel)
        self.btnRun.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.horizontalLayout.addWidget(self.btnRun)
        self.gridLayout.addWidget(self.bottomPanel, 20, 0, 1, 4)
        self.lblGeocoder = QtGui.QLabel(BatchGeocodingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblGeocoder.setFont(font)
        self.lblGeocoder.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Geocoder:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGeocoder.setObjectName(_fromUtf8("lblGeocoder"))
        self.gridLayout.addWidget(self.lblGeocoder, 17, 0, 1, 1)
        self.frmDistrict = QtGui.QFrame(BatchGeocodingDialog)
        self.frmDistrict.setEnabled(False)
        self.frmDistrict.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmDistrict.setFrameShadow(QtGui.QFrame.Raised)
        self.frmDistrict.setObjectName(_fromUtf8("frmDistrict"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frmDistrict)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbDisctrictName = QtGui.QRadioButton(self.frmDistrict)
        self.rbDisctrictName.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDisctrictName.setChecked(True)
        self.rbDisctrictName.setObjectName(_fromUtf8("rbDisctrictName"))
        self.gridLayout_2.addWidget(self.rbDisctrictName, 0, 0, 1, 1)
        self.rbDistrictField = QtGui.QRadioButton(self.frmDistrict)
        self.rbDistrictField.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "From field", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDistrictField.setChecked(False)
        self.rbDistrictField.setObjectName(_fromUtf8("rbDistrictField"))
        self.gridLayout_2.addWidget(self.rbDistrictField, 2, 0, 1, 1)
        self.txtDistrictName = QtGui.QLineEdit(self.frmDistrict)
        self.txtDistrictName.setObjectName(_fromUtf8("txtDistrictName"))
        self.gridLayout_2.addWidget(self.txtDistrictName, 0, 1, 1, 1)
        self.cmbDistrictField = QtGui.QComboBox(self.frmDistrict)
        self.cmbDistrictField.setEnabled(False)
        self.cmbDistrictField.setObjectName(_fromUtf8("cmbDistrictField"))
        self.gridLayout_2.addWidget(self.cmbDistrictField, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frmDistrict, 6, 1, 1, 3)
        self.chkRegion = QtGui.QCheckBox(BatchGeocodingDialog)
        self.chkRegion.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Region:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRegion.setObjectName(_fromUtf8("chkRegion"))
        self.gridLayout.addWidget(self.chkRegion, 4, 0, 1, 1)
        self.lblBuild = QtGui.QLabel(BatchGeocodingDialog)
        self.lblBuild.setText(QtGui.QApplication.translate("BatchGeocodingDialog", "Build. num:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBuild.setObjectName(_fromUtf8("lblBuild"))
        self.gridLayout.addWidget(self.lblBuild, 11, 0, 1, 1)

        self.retranslateUi(BatchGeocodingDialog)
        QtCore.QObject.connect(self.rbSettlField, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSettlField.setEnabled)
        QtCore.QObject.connect(self.rbSettlName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtSettlName.setEnabled)
        QtCore.QObject.connect(self.rbDistrictField, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDistrictField.setEnabled)
        QtCore.QObject.connect(self.rbDisctrictName, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtDistrictName.setEnabled)
        QtCore.QObject.connect(self.chkStreet, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbStreet.setEnabled)
        QtCore.QObject.connect(self.chkSettlement, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frmSettlement.setEnabled)
        QtCore.QObject.connect(self.chkDistrict, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frmDistrict.setEnabled)
        QtCore.QObject.connect(self.chkRegion, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbRegion.setEnabled)
        QtCore.QObject.connect(self.chkStreet, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbBuildingNum.setEnabled)
        QtCore.QObject.connect(self.chkStreet, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAddress.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(BatchGeocodingDialog)
        BatchGeocodingDialog.setTabOrder(self.cmbLayer, self.cmbAddress)
        BatchGeocodingDialog.setTabOrder(self.cmbAddress, self.chkRegion)
        BatchGeocodingDialog.setTabOrder(self.chkRegion, self.cmbRegion)
        BatchGeocodingDialog.setTabOrder(self.cmbRegion, self.chkDistrict)
        BatchGeocodingDialog.setTabOrder(self.chkDistrict, self.rbDisctrictName)
        BatchGeocodingDialog.setTabOrder(self.rbDisctrictName, self.txtDistrictName)
        BatchGeocodingDialog.setTabOrder(self.txtDistrictName, self.rbDistrictField)
        BatchGeocodingDialog.setTabOrder(self.rbDistrictField, self.cmbDistrictField)
        BatchGeocodingDialog.setTabOrder(self.cmbDistrictField, self.chkSettlement)
        BatchGeocodingDialog.setTabOrder(self.chkSettlement, self.rbSettlName)
        BatchGeocodingDialog.setTabOrder(self.rbSettlName, self.txtSettlName)
        BatchGeocodingDialog.setTabOrder(self.txtSettlName, self.rbSettlField)
        BatchGeocodingDialog.setTabOrder(self.rbSettlField, self.cmbSettlField)
        BatchGeocodingDialog.setTabOrder(self.cmbSettlField, self.chkStreet)
        BatchGeocodingDialog.setTabOrder(self.chkStreet, self.cmbStreet)
        BatchGeocodingDialog.setTabOrder(self.cmbStreet, self.cmbBuildingNum)
        BatchGeocodingDialog.setTabOrder(self.cmbBuildingNum, self.cmbGeocoder)
        BatchGeocodingDialog.setTabOrder(self.cmbGeocoder, self.btnRun)

    def retranslateUi(self, BatchGeocodingDialog):
        pass

